name = "dify2openai-cloudflare-worker"
main = "worker.js"
compatibility_date = "2024-06-14"

[env.production]
# 环境变量配置 - 在部署时需要设置这些变量
# 可以通过 Cloudflare Dashboard 或 wrangler secret put 命令设置

# 示例环境变量（需要在实际部署时配置）
# DIFY_API_URL = "https://api.dify.ai/v1"
# BOT_TYPE = "Chat"  # Chat, Completion, Workflow
# INPUT_VARIABLE = ""  # Workflow/Completion 模式下必填
# OUTPUT_VARIABLE = ""  # Workflow/Completion 模式下必填

[build]
command = ""

[build.upload]
format = "service-worker"
